// <auto-generated />
using System;
using HotelManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagement.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhan_phong");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("gio_nhan_phong");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tra_phong");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time")
                        .HasColumnName("gio_tra_phong");

                    b.Property<decimal?>("CleaningFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("phi_don_dep");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dat_coc");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int")
                        .HasColumnName("so_nguoi");

                    b.Property<int>("Nights")
                        .HasColumnType("int")
                        .HasColumnName("so_dem");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_moi_dem");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("phong_id");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("phi_dich_vu");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thue");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_dung_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("dat_phong", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("dat_phong_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("han_thanh_toan");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuong_thuc");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_thanh_toan");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("thanh_toan", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("dat_phong_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("binh_luan");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("phong_id");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("so_sao");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_dung_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("danh_gia", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("Id");

                    b.ToTable("vai_tro", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dien_tich");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_co_ban");

                    b.Property<int?>("BedCount")
                        .HasColumnType("int")
                        .HasColumnName("so_giuong");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("duoc_duyet");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_phong");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("co_so_id");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_phong");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.HasKey("Id");

                    b.ToTable("phong", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cccd");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_cuoi_hoat_dong");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_dang_nhap");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("vai_tro_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("nguoi_dung_vai_tro", (string)null);
                });

            modelBuilder.Entity("HotelManagement.API.Models.Booking", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Payment", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Review", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.UserRole", b =>
                {
                    b.HasOne("HotelManagement.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HotelManagement.API.Models.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HotelManagement.API.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
